### ISSUE TITLE
Fehler beim Connecten (uncaught exception)

### ISSUE THREAD

**Issue by b1rdhous3** [ruhigundrelaxed/ioBroker.hyperion#18]
Hallo, 

vielen Dank erstmal für den Adapter!

Ich habe aber leider ein Problem beim Einrichten: Wenn ich auf den JSON Port connecte bekomme ich folgenden Fehlerlog: 

```
host.osmc	2018-05-27 16:03:24.743	info	Restart adapter system.adapter.hyperion.0 because enabled
host.osmc	2018-05-27 16:03:24.743	error	instance system.adapter.hyperion.0 terminated with code 6 (uncaught exception)
host.osmc	2018-05-27 16:03:24.742	error	Caught by controller[0]: at TCP.onread (net.js:559:20)
host.osmc	2018-05-27 16:03:24.742	error	Caught by controller[0]: at Socket.Readable.push (_stream_readable.js:134:10)
host.osmc	2018-05-27 16:03:24.742	error	Caught by controller[0]: at readableAddChunk (_stream_readable.js:176:18)
host.osmc	2018-05-27 16:03:24.742	error	Caught by controller[0]: at Socket.emit (events.js:188:7)
host.osmc	2018-05-27 16:03:24.742	error	Caught by controller[0]: at emitOne (events.js:96:13)
host.osmc	2018-05-27 16:03:24.742	error	Caught by controller[0]: at Hyperion. (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/hyperion-client/lib/Hyperion.js:29:8)
host.osmc	2018-05-27 16:03:24.741	error	Caught by controller[0]: at Hyperion.parseData (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/hyperion-client/lib/Hyperion.js:51:31)
host.osmc	2018-05-27 16:03:24.741	error	Caught by controller[0]: at Array.forEach (native)
host.osmc	2018-05-27 16:03:24.741	error	Caught by controller[0]: at Hyperion. (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/hyperion-client/lib/Hyperion.js:64:16)
host.osmc	2018-05-27 16:03:24.740	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.hyperion/hyperion.js:330:105
host.osmc	2018-05-27 16:03:24.739	error	Caught by controller[0]: TypeError: Cannot read property '0' of undefined
hyperion.0	2018-05-27 16:03:23.857	info	cleaned everything up...
hyperion.0	2018-05-27 16:03:23.857	error	TypeError: Cannot read property '0' of undefined at /opt/iobroker/node_modules/iobroker.hyperion/hyperion.js:330:105 at Hyperion. (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/hyperion-client/lib/Hyperion.js:64:16) at Array.forEach (native) at Hyperion.parseData (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/hyperion-client/lib/Hyperion.js:51:31) at Hyperion. (/opt/iobroker/node_modules/iobroker.hyperion/node_modules/hyperion-client/lib/Hyperion.js:29:8) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at TCP.onread (net.js:559:20)
hyperion.0	2018-05-27 16:03:23.856	error	uncaught exception: Cannot read property '0' of undefined
hyperion.0	2018-05-27 16:03:23.371	info	Hooray! We are connected to hyperiond!
hyperion.0	2018-05-27 16:03:23.368	info	starting. Version 0.0.15 in /opt/iobroker/node_modules/iobroker.hyperion, node: v6.14.2
```

Wenn ich auf meinen Port von dem Hyperion Webinterface connecte bekomme ich keinen Fehler und der Adapter sagt mir, dass er zu Hyperion connected ist, aber dort scheint dann kein Befehl zu funktionieren. 
Ich gehe auch davon aus, dass man sich zum JSON Port connecten muss, aber ein Versuch war es wert. 

Sieht jemand einen Grund woran das liegen könnte?
Ich hab gedacht, dass es evtl. an der Version liegt (meine war von Juni letzten Jahres) Ich habe aber eben mal auf Grundlage des Gits neu gebaut. 

Vielen Dank im Voraus :)

**Comment by ruhigundrelaxed** [comment]
Ok. Habe den Titel des Issues angepasst. Leider habe ich den Adapter noch nicht für .ng fitt gemacht. Die Doku für .ng und dessen json interface ist noch nicht vorhanden. (Oder ich war blind...) Aber da ich auf kurz oder lang auch auf .ng wechseln möchte, lasse ich hier mal offen. Wenn jemand mir infos zur json Schnittstelle von .ng geben kann: Immer her damit.  Ich hoffe b1rdhous3 und andere stehen dann noch zum testen zur Verfügung.

**Comment by b1rdhous3** [comment]
Hi, 
ok, dann weiß ich bescheid. Bin gleich von .ng ausgegangen. 
"Zufälligerweise" habe ich an der Entwicklung von .ng mitgearbeitet. Ich habe am Webinterface gearbeitet und kann dir dementsprechend auch Hilfe zur JSON Schnittstelle geben. Nur weil ich noch nicht so die Ahnung von ioBroker Adaptern habe, dachte ich, ich frage direkt nach. 

Wenn du Hilfe bei der Migration auf .ng benötigst, helfe ich natürlich auch gern ;)

**Comment by ruhigundrelaxed** [comment]
Ja cool! Momentan benutze ich ein Modul (https://github.com/WeeJeWel/node-hyperion-client) um mit hyperion zu kommunizieren. Ich denke der sauberste Weg wäre dieses Modul zu aktualisieren, damit es auch mit .ng zusammen läuft. Ich werde mich die Tage mal damit beschäftigen... Wenn ich dann konkrete Fragen habe, komme ich auf dich zurück. Zum testen sowieso... :-) Danke schon mal...

**Comment by b1rdhous3** [comment]
Schau mal was ich die letzten Tage gebastelt habe... https://www.npmjs.com/package/hyperion-ng-api 
:-)

**Comment by ruhigundrelaxed** [comment]
Du bist der Hammer. :-)

**Comment by FalkPe** [comment]
https://github.com/felixganzer/ioBroker.hyperion_ng

💁
